### PR TITLE
improved the dark mode

### LINKED ISSUE #171: improve the dark mode
The dark mode only turn the main background black leaving the other elements the same making the page look displeasing.

The issue can be resolved by changing the color scheme of the elements appropriately.
Screenshot 2021-05-06 230801
above screenshot is the current dark mode.

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

improved the dark mode

Closes: #171 

### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/118914388-c04d3000-b948-11eb-9531-1543a479be29.mp4

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I am a GSSOC Participant.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
@vigneshshettyin have a look

**Comment by vigneshshettyin** [comment]
> 
> 
> @vigneshshettyin have a look

Hey, @arpit456jain pls format your edited files using Flake8 and Black (https://github.com/vigneshshettyin/Bulk-Mailer#lint-aformnd-at-)

**Comment by arpit456jain** [comment]
> > @vigneshshettyin have a look
> 
> Hey, @arpit456jain pls format your edited files using Flake8 and Black (https://github.com/vigneshshettyin/Bulk-Mailer#lint-aformnd-at-)

@vigneshshettyin i think that's for python code right ??

**Comment by vigneshshettyin** [comment]
> 
> 
> > > @vigneshshettyin have a look
> > 
> > 
> > Hey, @arpit456jain pls format your edited files using Flake8 and Black (https://github.com/vigneshshettyin/Bulk-Mailer#lint-aformnd-at-)
> 
> @vigneshshettyin i think that's for python code right ??

Yes

**Comment by arpit456jain** [comment]
@vigneshshettyin you can check i had add some code in base.html

I had not touched a single python file 😅

**Pull request merged**
