### PR TITLE
Add carousel to contributor section in landing page

### LINKED ISSUE #162: Add carousel to contributor section in landing page
### Is your feature request related to a problem? Please describe.
When contributors increase the page length automatically increase to avoid it, a carousel can be introduced to the contributors' section.

### Describe the solution you'd like
Implement carousel 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our other readers.

### Additional context
Some carousel libraries 
1. https://swiperjs.com/
2. https://owlcarousel2.github.io/OwlCarousel2/
3. https://kenwheeler.github.io/slick/

<hr/>

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

Add carousel to contributor section in landing page

Closes: #162 

### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/117413998-42465d80-af34-11eb-8d47-ed993c5cc3ec.mp4

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [] Any dependent changes have been merged and published in downstream modules.
- [x] I am a GSSOC Participant.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by vigneshshettyin** [comment]
> ## Related Issue
> Add carousel to contributor section in landing page
> 
> Closes: #162
> 
> ### Describe the changes you've made
>  2021-05-07.13-00-07.mp4 
> ## Type of change
> What sort of change have you made:
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Code style update (formatting, local variables)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> 
> ## Mention any unusual behaviour of your code (Write NA if not)
> Any unusual behaviour of your code
> 
> ## Checklist:
> * [x]  My code follows the guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented my code, particularly whereever it was hard to understand.
> * [x]  My changes generate no new warnings.
> * [] Any dependent changes have been merged and published in downstream modules.
> * [x]  I am a GSSOC Participant.
> 
> ## Additional Info (optional)
> Any additional information you want to give

Hey, one improvement required that is just to keep the GitHub logo in contributor card remove other socials. Also, remove the discoloration in links.  I'll change this issue to level 3. Kindly confirm on this @arpit456jain

**Comment by arpit456jain** [comment]
Ok but please explain a little bit about discoloration in link as i don't understand it correctly @vigneshshettyin

**Comment by vigneshshettyin** [comment]
> Ok but please explain a little bit about discoloration in link as i don't understand it correctly @vigneshshettyin

https://www.loom.com/share/d0198a77bcbc4fc6ad5af4fbe485dbff

**Comment by arpit456jain** [comment]
Should i Prevent the change in colour on Hover on icons??

**Comment by vigneshshettyin** [comment]
> Should i Prevent the change in colour on Hover on icons??

Just remove the underline which appears on hover. @arpit456jain

**Comment by arpit456jain** [comment]
Oh ok ok 👍👍

**Comment by arpit456jain** [comment]
Untitled

@vigneshshettyin

**Comment by arpit456jain** [comment]
@vigneshshettyin i had also remove the underline from social media icons in mentors section I hope that will be  fine

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR and add Level3 to it

**Review by vigneshshettyin — APPROVED** [review]

**Pull request merged**
