### PR TITLE
[Gssoc] Added confirmation for logout by sweet alert

### LINKED ISSUE #109: Confirmation before logout
I would like to add a modal for confirmation of logout. Like when user clicks on logout a modal will open and it will asks user 

Are you sure you want to logout !! 
Then use can click ok or cancel it

### PR DESCRIPTION
**Pull request by arpit456jain**
## Related Issue 

Added confirmation for logout by sweet alert in landing.html

Closes: #109 

### Describe the changes you've made
will upload a video
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I am a GSSOC Participant.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by arpit456jain** [comment]
@vigneshshettyin in Dashboard bootstrap modal is used for confirmation . should i change it to sweet alert or not
please confirm then i will make a video for my PR

**Comment by vigneshshettyin** [comment]
I'll merge it would be great if you could attach a demo video. @arpit456jain

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin in Dashboard bootstrap modal is used for confirmation . should i change it to sweet alert or not
> please confirm then i will make a video for my PR

Change it to sweet alert @arpit456jain

**Review by vigneshshettyin — APPROVED** [review]

**Comment by arpit456jain** [comment]
> > @vigneshshettyin in Dashboard bootstrap modal is used for confirmation . should i change it to sweet alert or not
> > please confirm then i will make a video for my PR
> 
> Change it to sweet alert @arpit456jain

@vigneshshettyin kindly add labels of GSSoC'21 and level 3 please 
And i will create a new issue for replacing the confirmation in dashboard to sweet alert in some time and will upload the video in 10 min

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/114980435-15110d00-9eaa-11eb-8f48-e828ac549cc9.mp4

**Pull request merged**
